// This file is automatically generated and contains assets from bepolia.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssetAggregators: Address[][];
}

export const USDT_ADDRESS = Address.fromString('0xF33aFBCeC8a104F3D1B7674cC16ebA96FeB9F905');
export const USDC_ADDRESS = Address.fromString('0x1F6A0b5659B11144d0e9F0A99184981815AFdD23');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xF33aFBCeC8a104F3D1B7674cC16ebA96FeB9F905'), // USDT
    Address.fromString('0x1F6A0b5659B11144d0e9F0A99184981815AFdD23'), // USDC
  ],
  pricingAssets: [
  ],
  fxAssetAggregators: [
  ],
};
