// This file is automatically generated and contains assets from amoy.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssetAggregators: Address[][];
}

export const USDC_ADDRESS = Address.fromString('0x07b655e4005804afB03986ceF4E611D63Eaac010');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x07b655e4005804afB03986ceF4E611D63Eaac010'), // USDC
  ],
  pricingAssets: [
  ],
  fxAssetAggregators: [
    [
      Address.fromString('0x07b655e4005804afB03986ceF4E611D63Eaac010'), // USDC
      Address.fromString('0x1aF00782F74DdC4c7fCEFe8752113084FEBCDA45'), // USDC/USD
    ],
    [
      Address.fromString('0x4be0A15F36057b13022050753d09B6663837f963'), // PHX
      Address.fromString('0x3251e99cEf4b9bA03a6434B767aa5Ad11ca6cc31'), // PHX/USD
    ],
    [
      Address.fromString('0x9072828ff0c62311D522B0F0aa1C5ad72F5F8Ce0'), // PHPC
      Address.fromString('0x3251e99cEf4b9bA03a6434B767aa5Ad11ca6cc31'), // PHPC/USD
    ],
  ],
};
