name: Deploy Hosted Service Prod

on:
  push:
    branches: master

jobs:
  deploy-goerli:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets goerli
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-goerli-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.goerli.yaml"
  deploy-mainnet:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.yaml"
  deploy-polygon:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets polygon
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-polygon-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.polygon.yaml"
  deploy-polygon-pruned:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets polygon-prune
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-polygon-prune-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.polygon.pruned.yaml"
  deploy-arbitrum:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets arbitrum
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-arbitrum-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.arbitrum.yaml"
  deploy-gnosis:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets gnosis
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-gnosis-chain-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.gnosis.yaml"
  deploy-bnb:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets bnb
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-bnbchain-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.bnb.yaml"
  deploy-avalanche:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets avalanche
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-avalanche-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.avalanche.yaml"
  deploy-optimism:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets optimism
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-optimism-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.optimism.yaml"

env:
  CI: true
